name: Build Project
on: [push]
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build project
        run: .\build.bat
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: ESOLua
          path: output