name: Build Project
on: [push]
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build executable
        run: make mingw
      - name: Create output folder
        run: md output
      - name: Copy artifacts
        run: |
          robocopy src output *.exe *.dll
          robocopy . output COPYRIGHT HISTROY INSTALL README
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: ESOLua
          path: output