name: Build Project
on: [push]
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build executable
        run: make mingw
      - name: Create output folder
        run: md output
      - name: Copy artifacts
        run: |
          robocopy src output *.exe *.dll
          robocopy . output COPYRIGHT HISTORY INSTALL README
          if ErrorLevel 8 (exit /B 1) else (exit /B 0)
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: ESOLua
          path: output